// metadata.js
export const Metadata = {
    title: "Translo || Responsive Next Template",
    description: "Generated by create next app",
    icons: {
      icon: ["/favicon.ico?v=4"],
      apple: ["/favicon.ico?v=4"],
      shortcut: ["/favicon.ico"],
    },
  };
  